spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: monitor
      password: emt123#!
      jdbc-url: jdbc:mysql://172.17.88.11/monitor?characterEncoding=utf-8&useSSL=false
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      username: fee
      password: fee123#!
      jdbc-url: jdbc:mysql://172.16.0.17/monitor?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /fees
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    template-loader-path: classpath:/templates
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  port: 6998
