spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: emt
    password: emt123#!
    url: jdbc:mysql://127.0.0.1/fees?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /fees
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    template-loader-path: classpath:/templates
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl